services:
  # WORKER 1: The Web Server (Django)
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # This automatically loads everything in your .env file
    environment:
      - DB_HOST=db
      - DB_NAME=smartdoc_db
      - DB_USER=smartdoc_user
      - DB_PASS=supersecretpassword
      - CELERY_BROKER_URL=redis://redis:6379/0

  # WORKER 2: The Database (PostgreSQL with pgvector)
  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=smartdoc_db
      - POSTGRES_USER=smartdoc_user
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # WORKER 3: The Task Queue (Redis)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # WORKER 4: The Background Worker (Celery)
  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env  # MUST be here too so the background tasks can access Groq
    environment:
      - DB_HOST=db
      - DB_NAME=smartdoc_db
      - DB_USER=smartdoc_user
      - DB_PASS=supersecretpassword
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data: